# Hyperparameters for the model
# --- 
model:
  n_estimators: 100
  max_depth: 5
  random_state: 42
  n_jobs: -1
  oob_score: True
  verbose: 0
  criterion: gini
  class_weight: balanced
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: auto
  max_leaf_nodes: None
  
